### ISSUE TITLE
some strange errors

### ISSUE THREAD

**Issue by vtolstov** [segmentio/kafka-go#433]
**Describe the solution you'd like**
When i'm test service under load, i get strange errors like:

```
failed to read from current broker for partition 0 of TOPIC at offset 7478, not the leader
```

```
publication to topic TOPIC error: [6] Not Leader For Partition: the client attempted to send messages to a replica that is not the leader for some partition, the client's metadata are likely out of date
```

```
error writing messages to TOPIC (partition 2): [2] Invalid Message: the message contents does not match its CRC
```

Can you explain why it happening, and how to deal with "not a leader"
And how to set metadata update duration?

**Comment by achille-roussel** [comment]
Hello @vtolstov.

The first error may occur when a partition leader is being elected, it takes a bit of time for the clients to update their views of the clusters and reroute new messages to the right brokers.

For the second error, would you be able to let me know which version of kafka-go you were using?

**Comment by vtolstov** [comment]
This is older kafka-go.
Mostly it happens when kafka server is slowdown

**Comment by kshetty1990** [comment]
Hi 

I am also seeing same errors. Please let me know how to fix this.

`Kafka (consume): unable to read message from consumer <topic name>- [6] Not Leader For Partition: the client attempted to send messages to a replica that is not the leader for some partition, the client’s metadata are likely out of date

Kafka (consume): unable to read message from consumer SCCM-Dev - unexpected EOF`

I am using kafka-go v0.4.8

Thanks!

**Comment by vtolstov** [comment]
mostly solved by minimize kafka client-server latency and rework my code

**Comment by lionelfr** [comment]
I'm still getting this issue after rewriting my kafka-client code so the latency is minimized, any chance this can be solved without having to retry the connection?

**Comment by vtolstov** [comment]
you can try to use latest kafka-go release as devs fixed some temp errors handling

**Comment by znjuko** [comment]
Hello everyone!
Im using v0.4.31 of `github.com/segmentio/kafka-go`

Still getting errors like

`[6] Not Leader For Partition: the client attempted to send messages to a replica that is not the leader for some partition, the client's metadata are likely out of date`

and also
`failed to dial: failed to open connection to :0: dial tcp :0: connect: connection refused`


Do i have to upgrade to v0.4.35 or this bug is kind of bad config?
