### ISSUE TITLE
Reading topic partitions stopped at specific offsets

### ISSUE THREAD

**Issue by OhohLeo** [segmentio/kafka-go#621]
We use kafka 2.6 & segmentio v0.4.12 (but we reproduce this issue on master branch too).

We are consuming a topic having 10 partitions with a simple program called avro-reader : 
```
GROUP           TOPIC                        PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG            
avro-reader     qv3sync.uuids.to.ids.changes 0          19820831        19820856        25             
avro-reader     qv3sync.uuids.to.ids.changes 1          5719209         19824901        14105692       
avro-reader     qv3sync.uuids.to.ids.changes 2          5735913         19825060        14089147       
avro-reader     qv3sync.uuids.to.ids.changes 3          19826131        19826170        39             
avro-reader     qv3sync.uuids.to.ids.changes 4          8141344         19821910        11680566       
avro-reader     qv3sync.uuids.to.ids.changes 5          8141618         19831628        11690010       
avro-reader     qv3sync.uuids.to.ids.changes 6          19830374        19830407        33             
avro-reader     qv3sync.uuids.to.ids.changes 7          5723818         19824549        14100731       
avro-reader     qv3sync.uuids.to.ids.changes 8          8926384         19824663        10898279       
avro-reader     qv3sync.uuids.to.ids.changes 9          4286435         19828306        15541871       
```

The main issue is that partitions 0, 3 & 6 are fully synced but other partitions stopped to be read.

We use kafkacat to see what is happening and we observe that there are some offset jumps but kafkacat can manage to read the next offset. 

Here are the previous and next message around the offset that where segmentio could not decode : 
```
# Partition 1 offset 5719209
1606765019807 qv3sync.uuids.to.ids.changes(1/5719208) 905bd1cb-8499-4092-b5ef-c38d07de2cd9 => {"instance": "QOS", "type": "Event", "id": 257462080}
1606765019821 qv3sync.uuids.to.ids.changes(1/5719224) 58efef04-e21c-4768-9902-e4381ee38189 => {"instance": "QOS", "type": "Event", "id": 257462551}

# Partition 2 offset 5735913
1606765015761 qv3sync.uuids.to.ids.changes(2/5735912) a05d68dc-712f-4a81-96bf-587cf00a5060 => {"instance": "QOS", "type": "Event", "id": 257376813}
1606765043854 qv3sync.uuids.to.ids.changes(2/5735949) cf4fa5fc-fd66-4185-8663-699c5912dd04 => {"instance": "QOS", "type": "Event", "id": 257968767}

# Partition 4 offset 19821910
1607771769222 qv3sync.uuids.to.ids.changes(4/8141343) bd544c4d-af4a-4de9-a2fa-4f65cf17c381 => {"instance": "QOS", "type": "Event", "id": 271624286}
1607771778222 qv3sync.uuids.to.ids.changes(4/8141351) 9520a69a-6f6b-4cba-a735-1db546cb3790 => {"instance": "QOS", "type": "Event", "id": 271624412}

# Partition 5 offset 8141618
1607769385221 qv3sync.uuids.to.ids.changes(5/8141617) 860de689-7536-4f02-8cf9-d5696efd1bb1 => {"instance": "QOS", "type": "Event", "id": 271596286}
1607769415221 qv3sync.uuids.to.ids.changes(5/8141649) 0ad23a9a-0530-408b-ba89-15e4c90cc557 => {"instance": "QOS", "type": "Event", "id": 271596565}

# Partition 7 offset 5723818
1606765400936 qv3sync.uuids.to.ids.changes(7/5723817) 12d5e710-232c-4274-893d-e207966ba06e => {"instance": "QOS", "type": "Event", "id": 265308709}
1606764843641 qv3sync.uuids.to.ids.changes(7/5723822) a05caa73-6451-4867-bcaf-c31e69da5a62 => {"instance": "QOS", "type": "Event", "id": 253855766}

# Partition 8 offset 8926384
1608381334242 qv3sync.uuids.to.ids.changes(8/8926383) ee8c8fe6-705c-4304-aeeb-744e3d4ad38b => {"instance": "EU2", "type": "Event", "id": 17089599}
1608381349221 qv3sync.uuids.to.ids.changes(8/8926438) a13f8d3c-90f3-4e2a-aa38-cf26e8c189b9 => {"instance": "QOS", "type": "Event", "id": 274821811}

# Partition 9 offset 4286435
1606764243130 qv3sync.uuids.to.ids.changes(9/4286434) e74408e4-5b6c-420e-805e-8d37735a6e18 => {"instance": "QOS", "type": "Event", "id": 182882120}
1606764740241 qv3sync.uuids.to.ids.changes(9/4286436) 6d546a6e-a726-4dd8-8b1e-1e42786faba5 => {"instance": "QOS", "type": "Event", "id": 251782590}
```

We investigate on the segmentio library but our deep knowledged on kafka API is still limitated and you may have some suggestions.

We focus on partition 2 and offset 5735913 issue and it seems that : 
 - A request at offset 5735913 is made on Kafka API 
 - Kafka API response with no error
 - 1st received message seems correctly received (message at offset 5735912)
 - Next message failed because no bytes remaining
 - A request at offset 5735913 is made on Kafka API (again)
 
This process is repeated again and again...

Here are some logs I manage to set for our investigation : 
```
***** reader.go read() offset:5735913 partition:2
conn.go ReadBatchWith() fetchVersion: 10 cfg.MinBytes:1 cfg.MaxBytes:10000000 maxFetch:2147483561 partition: 2
conn.go ReadBatchWith() -> writeFetchRequestV10() id:9 clientID:avro-reader.git@lmartin-ASUS-P3540FA (github.com/segmentio/kafka-go) partition:2
conn.go c.doRequest() partition:2 id:9 offset:5735913  err:<nil>
conn.go c.waitResponse()  c.partition:2 size:282 err:<nil>
conn.go readFetchResponseHeaderV10()  c.partition:2 throttle:0 highWaterMark:19868680 remain:196 err:<nil>
message.go -> newMessageSetReader() version:2 remain:196
conn.go newMessageSetReader()  c.partition:2 throttle:0 highWaterMark:19868680 remain:196 msgs:&{empty:false version:2 v1:{readerStack:<nil>} v2:{readerStack:0xc00059a600 messageCount:0 header:{firstOffset:0 length:0 partitionLeaderEpoch:0 magic:0 crc:0 batchAttributes:0 lastOffsetDelta:0 firstTimestamp:0 maxTimestamp:0 producerId:0 producerEpoch:0 firstSequence:0}}} err:<nil>
batch.go ReadMessage() -> batch.readMessage KEY key:a05d68dc-712f-4a81-96bf-587cf00a5060 remain:93 error:<nil>
batch.go ReadMessage() -> batch.readMessage VALUE value:[0 0 0 0 42 6 81 79 83 10 69 118 101 110 116 218 136 186 245 1] remain:72 error:<nil>
batch.go readMessage() -> batch.msgs.readMessage() batch.offset:5735913 offset:5735912 partition:2 error:<nil>
batch.go ReadMessage() -> batch.readMessage offset:5735912 batchOffset: 5735913 partition:2 error:<nil>
[FAILED] message.go -> readMessage() -> readHeader()  err: not enough bytes available to load the response
batch.go readMessage() -> batch.msgs.readMessage() batch.offset:5735913 offset:0 partition:2 error:not enough bytes available to load the response
batch.go readMessage() -> case errShortRead offset:0 partition:2 error:not enough bytes available to load the response
message.go discard() remain:0, error: <nil>
batch.go readMessage() -> discard() offset:0 partition:2 error:<nil>
batch.go readMessage() -> batch.msgs.remaining() -> checkTimeoutErrr offset:0 partition:2 error:EOF
batch.go ReadMessage() batch.conn != nil -> batch.readMessage offset:0 partition:2 error:EOF
batch.go ReadMessage() msg:{Topic:qv3sync.uuids.to.ids.changes Partition:2 Offset:0 HighWaterMark:19868680 Key:[97 48 53 100 54 56 100 99 45 55 49 50 102 45 52 97 56 49 45 57 54 98 102 45 53 56 55 99 102 48 48 97 53 48 54 48] Value:[0 0 0 0 42 6 81 79 83 10 69 118 101 110 116 218 136 186 245 1] Headers:[] Time:0001-01-01 00:00:00 +0000 UTC} error:EOF
******* [FAILED] reader.go read() -> batch.ReadMessage() offset:5735913 partition:2 error:EOF
message.go discard() remain:0, error: <nil>
```

 - You may have some advice/suggestion about this issue ?
 - We could do more tests to deeply investigate ?
 - What do you suggest to fix this kind of issues ?

Kind Regards,
Leo Martin (QOS Energy)

**Comment by achille-roussel** [comment]
Hello @OhohLeo, thanks for opening the issue!

This does look like a bug, the client shouldn't have requested offset 5735913 again if it had successfully consumed it already.

Would you happen to have a way to reproduce this issue? Or maybe more details about the setup:
- Are you using a consumer group or do you have the reader statically configured to read from one partition?
- What was the size of the message at offset 5735913?
- Could you share the configuration of your reader?

**Comment by OhohLeo** [comment]
Hi!

Concerning our configuration : 
 - we use a consumer group
 - we use default reader configurations (we specify only topic name & groupID)

Here are some informations about what is it sent & received from kafka at offset 5735913 : 

We sent a request to kafka on writeFetchRequestV10() method (write.go) : 
```
correlationID:8 
clientID:avro-reader.git@lmartin-ASUS-P3540FA (github.com/segmentio/kafka-go) 
topic:qv3sync.uuids.to.ids.changes 
partition:2 
offset:5735913 
minBytes:1 
maxBytes:10000086 
maxWait:8.999942562s 
isolationLevel:0
```

We received following bytes from kafka : 
```
conn.go c.waitResponse()  c.partition:2 size:282 err:<nil>
 rcv: [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 28 113 118 51 115 121 110 99 46 117 117 105 100 115 46 116 111 46 105 100 115 46 99 104 97 110 103 101 115 0 0 0 1 0 0 0 2 0 0 0 0 0 0 1 62 77 147 0 0 0 0 1 62 77 147 0 0 0 0 0 0 0 0 255 255 255 255 0 0 0 196 0 0 0 0 0 87 133 232 0 0 0 184 0 0 0 0 2 118 251 226 149 0 0 0 0 0 1 0 0 1 118 26 168 114 209 0 0 1 118 26 168 114 209 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 1 138 2 0 0 0 72 97 48 53 100 54 56 100 99 45 55 49 50 102 45 52 97 56 49 45 57 54 98 102 45 53 56 55 99 102 48 48 97 53 48 54 48 40 0 0 0 0 42 6 81 79 83 10 69 118 101 110 116 218 136 186 245 1 6 28 100 101 98 101 122 105 117 109 45 115 116 97 116 101 14 67 82 69 65 84 69 68 20 115 116 97 114 116 101 100 95 97 116 26 49 54 48 53 48 50 48 52 53 54 48 48 48 16 101 110 100 101 100 95 97 116 26 49 54 48 53 48 50 48 53 51 53 48 48 48]
```

This received buffer is used by :
 - readFetchResponseHeaderV10 seems correctly decoded
```
conn.go readFetchResponseHeaderV10()  c.partition:2 throttle:0 offset:5735913 highWaterMark:20860309 remain:196 err:<nil>
```
 - newMessageSetReader seems also correctly decoded (but we received offset 5735912 instead of 5735913)
```
message.go -> newMessageSetReader() [remain:196] [0 0 0 0 0 87 133 232 0 0 0 184 0 0 0 0 2 118 251 226 149 0 0 0 0 0 1 0 0 1 118 26 168 114 209 0 0 1 118 26 168 114 209 255 255 255 255 255 255 255 255 255 255 255 255 255 255 0 0 0 1 138 2 0 0 0 72 97 48 53 100 54 56 100 99 45 55 49 50 102 45 52 97 56 49 45 57 54 98 102 45 53 56 55 99 102 48 48 97 53 48 54 48 40 0 0 0 0 42 6 81 79 83 10 69 118 101 110 116 218 136 186 245 1 6 28 100 101 98 101 122 105 117 109 45 115 116 97 116 101 14 67 82 69 65 84 69 68 20 115 116 97 114 116 101 100 95 97 116 26 49 54 48 53 48 50 48 52 53 54 48 48 48 16 101 110 100 101 100 95 97 116 26 49 54 48 53 48 50 48 53 51 53 48 48 48]
message.go -> newMessageSetReader() version:2 remain:196
batch.go ReadMessage() -> readMessage() KEY size:129 nbytes:36
batch.go ReadMessage() -> batch.readMessage KEY key:a05d68dc-712f-4a81-96bf-587cf00a5060 remain:93 error:<nil>
batch.go ReadMessage() -> readMessage() VALUE size:92 nbytes:20
batch.go ReadMessage() -> batch.readMessage VALUE value:[0 0 0 0 42 6 81 79 83 10 69 118 101 110 116 218 136 186 245 1] remain:72 error:<nil>
```
 - not enough bytes available to load the response issue is generated from following methods : 
    - https://github.com/segmentio/kafka-go/blob/v0.4.12/batch.go#L197
    - https://github.com/segmentio/kafka-go/blob/v0.4.12/batch.go#L228
    - https://github.com/segmentio/kafka-go/blob/v0.4.12/message.go#L478

It seems that message at offset 5735913 doesn't exist I my case. 

To decode received kafka frame, is it this documentation? : https://kafka.apache.org/documentation/#recordbatch.

I will stop searching for today but here is my current investigation step.

**Comment by OhohLeo** [comment]
Hi again,
Any news about this bug? 
Could you tell us what do you think about this bug ? Could it be fixed?

On our side, we will try to fix this bug because we use this library on production and we won't be happy that this bug happened on week-end.

**Comment by leedavis81** [comment]
I've witnessed a similar issue and our grouped consumer seems to stop advancing on certain partitions.

Where we're continuing a grouped consumer on from a marked offset that no longer exists (possibly compacted away) the consumer attempts to read up to that offset, and will only reset the batch buffer once it can match that offset to the highwatermark: https://github.com/segmentio/kafka-go/blob/master/conn.go#L871-L875

As we read a batch we see the following behaviour as kafka-go attempts to parse out messages. On the first message read of the batch our message count is zero, so the header is processed giving us:

```
(kafka.messageSetHeaderV2) {
 firstOffset: (int64) 1270841,
 length: (int32) 10655,
 partitionLeaderEpoch: (int32) 38,
 magic: (int8) 2,
 crc: (int32) 1434432957,
 batchAttributes: (int16) 0,
 lastOffsetDelta: (int32) 7,
 firstTimestamp: (int64) 1615586157377,
 maxTimestamp: (int64) 1615586157377,
 producerId: (int64) -1,
 producerEpoch: (int16) -1,
 firstSequence: (int32) 0
}
```

along with the first record of our batch at offset 1270841

we now have remaining bytes set to 10606 and a message count of 6. the consumer then continues to iterate through the messages in that batch...


```
offset: 1270842
remaining bytes: 8884
message count: 5

offset: 1270843
remaining bytes: 7162
message count: 4

offset: 1270844
remaining bytes: 5424
message count: 3

offset: 1270846 (1270845 isn't present)
remaining bytes: 3661
message count: 2

offset: 1270847
remaining bytes: 1790
message count: 1
```

The message count is now 0 and we have no remaining bytes in the buffer, however as the offset has been advanced and we've still not hit the high watermark yet (because that record is gone) the consumer then calls `batch.readMessage()` and subsequently `messageSetReaderV2.readMessage()` where it falls into the condition of trying to read header information with no remaining bytes: https://github.com/segmentio/kafka-go/blob/master/message.go#L478

This then triggers the 'not enough bytes available to load the response' error, preventing the offset from advancing and the consumer continues to loop on reading the same batch.

**Comment by iddqdeika** [comment]
problem is that batch doesn't contain the offset which batch expects.
`batch.conn != nil && offset < batch.conn.offset` condition still returns `true`, but readerStack.remain equals 0.
somehow kafka returned batch without message having offset from Fetch request...
solution can be to increment con.offset by 1 in cate successfully read batch contains 0 new messages.

just like in sarama's partitionConsumer.parseMessages

**Comment by nlsun** [comment]
This issue is fixed in https://github.com/segmentio/kafka-go/pull/813

**Comment by nlsun** [comment]
@OhohLeo @leedavis81 @iddqdeika the fix is included in https://github.com/segmentio/kafka-go/releases/tag/v0.4.28

**Comment by iddqdeika** [comment]
@nlsun still reproducing this bug. sometimes batch.lastoffset is < or > 0 at the point there we meet EOF on compacted records.

**Comment by iddqdeika** [comment]
stil don't have anough time to reproduce in intergation tests. 

it consistently reproduces in our test environment.

but when i changed in batch.go
`if batch.err == io.EOF && batch.msgs.lengthRemain == 0 && batch.lastOffset != -1`
to 
'if batch.err == io.EOF && batch.msgs.lengthRemain <= 0 && batch.lastOffset != -1'

it seems to work fine.

**Comment by nlsun** [comment]
@iddqdeika when you get a chance can you try printing the offset when:
- `batch.msgs.lengthRemain <= 0`
- we set the initial lengthRemain https://github.com/segmentio/kafka-go/blob/b952e635d4f1b688854c1097cd7ce6eeaf50b273/message_reader.go#L468
- we update the lengthRemain https://github.com/segmentio/kafka-go/blob/b952e635d4f1b688854c1097cd7ce6eeaf50b273/message_reader.go#L328

**Comment by deanMdreon** [comment]
Are there any updates to this issue? I am seeing the same behavior in version v0.4.29

**Comment by nlsun** [comment]
@deanMdreon are you able to reproduce your issue in a test case? Does the workaround that @iddqdeika pasted work in your case? Would be good to know if you are facing the same or a different issue

**Comment by iddqdeika** [comment]
> Are there any updates to this issue? I am seeing the same behavior in version v0.4.29

currentry I have in use this fix:
if batch.err == io.EOF && batch.msgs.lengthRemain == 0 && batch.lastOffset != -1
to
if batch.err == io.EOF && batch.msgs.lengthRemain <= 0 && batch.lastOffset != -1

but still don't have enough time to reproduce problem via integration test =(

You can try to add this directive to your go.mod file:
 `replace github.com/segmentio/kafka-go v0.4.28 => github.com/iddqdeika/kafka-go v0.4.28-fix`

and let us know would this help in your case. 
thanks!

**Comment by deanMdreon** [comment]
Our issue ended up being something different, outside of the library.
