### ISSUE TITLE
"unexpected EOF" error getting logged consistently when consumer waiting on a topic

### ISSUE THREAD

**Issue by discovery-haridasNarayanaswamy** [segmentio/kafka-go#830]
**Describe the bug**
Kafka consumer throwing below error consistently, it's able to read messages but after some wait time, this error start coming.

```
Kafka >> reader.go:1380: the kafka reader got an unknown error reading partition 0 of <topic_name> at offset 0: unexpected EOF
```
This error comes for all the partitions under the given topic in constant intervals. Looks like the connection reset by the reader threads.

**Kafka Version**
Kafka version : `2.6.1`

**To Reproduce**

Having standard consumer, and run it for a couple of minutes. The topic we are using low traffic is one or very few messages now.

**Expected behavior**
No warning or such logs should pump out to stdout/stderr

**Additional context**
Using TLS / ACL to authenticate with the cluster.

**Comment by rhansen2** [comment]
Hi @discovery-haridasNarayanaswamy,

What version of the library are you using? We had a bug that was fixed in v0.4.26 that caused behavior like this when the topic has no more message to process.

**Comment by discovery-haridasNarayanaswamy** [comment]
@rhansen2  I'm using`v0.4.25`. Upgraded it to `v0.4.27`, we are seeing this error still. Our topic is very low volume, few messages per day.

**Comment by rhansen2** [comment]
Are you able to provide a reproduction? I'm not able to reproduce by running a Reader against a topic with no messages.

**Comment by rhansen2** [comment]
Closing due to inactivity, feel free to reopen if the issue persists.
